import "./style.css";
import "./src/js/alpine.js";

import imageMacbook from "./src/img/macbook.jpg?w=700&format=webp";
import imageBoonstra from "./src/img/boonstra.jpg?w=600&h=600&format=webp";
import imageWNC from "./src/img/wnc.jpg?w=600&h=600&format=webp";
import imageVos from "./src/img/vos.jpg?w=600&h=600&format=webp";
import imageCeres from "./src/img/ceres.jpg?w=600&h=600&format=webp";
import imageSander from "./src/img/sander.jpg?w=100&h=100&format=webp";
import logoBM from "./src/img/logos/bm.png?format=webp";
import logoDrumlin from "./src/img/logos/drumlin.png?format=webp";
import logoKSF from "./src/img/logos/ksf.png?format=webp";
import logoSmaakgroen from "./src/img/logos/smaakgroen.png?format=webp";
import logoVos from "./src/img/logos/vos.png?format=webp";
import logoWNC from "./src/img/logos/wnc.png?format=webp";
import logoZP from "./src/img/logos/zp.png?format=webp";

document.getElementById("image-macbook").src = imageMacbook;
document.getElementById("image-boonstra").src = imageBoonstra;
document.getElementById("image-wnc").src = imageWNC;
document.getElementById("image-vos").src = imageVos;
document.getElementById("image-ceres").src = imageCeres;
document.getElementById("image-sander").src = imageSander;
document.getElementById("logo-bm").src = logoBM;
document.getElementById("logo-drumlin").src = logoDrumlin;
document.getElementById("logo-ksf").src = logoKSF;
document.getElementById("logo-smaakgroen").src = logoSmaakgroen;
document.getElementById("logo-vos").src = logoVos;
document.getElementById("logo-wnc").src = logoWNC;
document.getElementById("logo-zp").src = logoZP;
